version: "3.9"
services:
  backend:
    build: .
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    ports:
      - "8080:80"
    volumes:
      - assets:/app/assets  
    restart: always  
